// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient } from "npm:@supabase/supabase-js@^2.93.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Soul Fuel member's profile: id, name, email, roles, and membership status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const sb = supabaseForUser(ctx);
    const [{ data: profile, error: pErr }, { data: roles, error: rErr }] = await Promise.all([
      sb.from("profiles").select("id, full_name, subscription_status, selected_plan, membership_expires_at, intake_submitted, intake_requested").eq("id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId)
    ]);
    if (pErr || rErr) {
      return { content: [{ type: "text", text: (pErr ?? rErr).message }], isError: true };
    }
    const result = {
      id: userId,
      email: ctx.getUserEmail() ?? null,
      full_name: profile?.full_name ?? null,
      roles: (roles ?? []).map((r) => r.role),
      subscription_status: profile?.subscription_status ?? null,
      selected_plan: profile?.selected_plan ?? null,
      membership_expires_at: profile?.membership_expires_at ?? null,
      intake_submitted: profile?.intake_submitted ?? false,
      intake_requested: profile?.intake_requested ?? false
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-upcoming-sessions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_sessions_default = defineTool2({
  name: "list_upcoming_sessions",
  title: "List my upcoming sessions",
  description: "List the signed-in Soul Fuel member's upcoming coaching sessions (scheduled and not yet completed).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of sessions to return. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = limit ?? 10;
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("session_attendees").select("session_id, sessions!inner(id, title, scheduled_for, status, note)").eq("user_id", ctx.getUserId()).gte("sessions.scheduled_for", (/* @__PURE__ */ new Date()).toISOString()).neq("sessions.status", "completed").neq("sessions.status", "didnt_happen").order("scheduled_for", { referencedTable: "sessions", ascending: true }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => r.sessions);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { sessions: rows }
    };
  }
});

// src/lib/mcp/tools/list-daily-dose.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_daily_dose_default = defineTool3({
  name: "list_daily_dose",
  title: "List recent Daily Dose posts",
  description: "List recent published Soul Fuel Daily Dose posts visible to the signed-in member.",
  inputSchema: {
    limit: z2.number().int().min(1).max(30).optional().describe("Maximum number of posts to return. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = limit ?? 10;
    const sb = supabaseForUser3(ctx);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await sb.from("daily_dose_posts").select("id, title, content, publish_date, audience_user_id").lte("publish_date", today).order("publish_date", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cmnbveoxckkgmhcxmwgm";
var mcp_default = defineMcp({
  name: "soul-fuel-society-mcp",
  title: "Soul Fuel Society",
  version: "0.1.0",
  instructions: "Tools for a signed-in Soul Fuel Society member. Use `whoami` to fetch the member's profile and roles, `list_upcoming_sessions` to see their scheduled coaching sessions, and `list_daily_dose` to read recent Daily Dose posts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_upcoming_sessions_default, list_daily_dose_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
